# Generated by Django 5.2.7 on 2026-02-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0002_pokemon_image_alter_pokemon_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokePokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='широта покемона')),
                ('lon', models.FloatField(verbose_name='долгота покемона')),
            ],
        ),
    ]
