# Generated by Django 5.2.7 on 2026-02-28 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_pokepokemonentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokepokemonentity',
            name='appeared_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время появления покемона'),
        ),
        migrations.AddField(
            model_name='pokepokemonentity',
            name='attack',
            field=models.IntegerField(blank=True, null=True, verbose_name='Атака покемона'),
        ),
        migrations.AddField(
            model_name='pokepokemonentity',
            name='disappeared_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время исчезновения покемона'),
        ),
        migrations.AddField(
            model_name='pokepokemonentity',
            name='endurance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Выносливость покемона'),
        ),
        migrations.AddField(
            model_name='pokepokemonentity',
            name='health',
            field=models.IntegerField(blank=True, null=True, verbose_name='Здоровье покемона'),
        ),
        migrations.AddField(
            model_name='pokepokemonentity',
            name='level',
            field=models.IntegerField(blank=True, null=True, verbose_name='Уровень покемона'),
        ),
        migrations.AddField(
            model_name='pokepokemonentity',
            name='pokemon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='pokemon_entities.pokemon', verbose_name='ссылка на покемона'),
        ),
        migrations.AddField(
            model_name='pokepokemonentity',
            name='protection',
            field=models.IntegerField(blank=True, null=True, verbose_name='Защита покемона'),
        ),
        migrations.AlterField(
            model_name='pokepokemonentity',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='широта покемона'),
        ),
        migrations.AlterField(
            model_name='pokepokemonentity',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='долгота покемона'),
        ),
    ]
